- name: Rename macOS app
  run: |
    mv build/macos/Build/Products/Release/Runner.app build/macos/Build/Products/Release/C-TCC_MAPENDO.app

- name: Zip macOS app
  run: |
    cd build/macos/Build/Products/Release
    zip -r C-TCC_MAPENDO-macOS.zip C-TCC_MAPENDO.app

- name: Upload macOS artifact
  uses: actions/upload-artifact@v4
  with:
    name: C-TCC_MAPENDO-macOS
    path: build/macos/Build/Products/Release/C-TCC_MAPENDO-macOS.zip
